package org.family.pojo;

public class Motor extends MotorKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_USERNAME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_MOBILE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_CARDID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorCardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_PLATE_NUMBER
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorPlateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_ENGINE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorEngine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_TYPE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private Integer motorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_COLOR
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.MOTOR_MODEL
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String motorModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.IS_SCRAP
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String isScrap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.IS_DELETE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.CREAT_USER_ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private Integer creatUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.CREAT_TIME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.EDIT_USER_ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private Integer editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.EDIT_TIME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private String editTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_USERNAME
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_USERNAME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorUsername() {
        return motorUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_USERNAME
     *
     * @param motorUsername the value for TRAFFIC_MOTOR.MOTOR_USERNAME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorUsername(String motorUsername) {
        this.motorUsername = motorUsername == null ? null : motorUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_MOBILE
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_MOBILE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorMobile() {
        return motorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_MOBILE
     *
     * @param motorMobile the value for TRAFFIC_MOTOR.MOTOR_MOBILE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorMobile(String motorMobile) {
        this.motorMobile = motorMobile == null ? null : motorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_CARDID
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_CARDID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorCardid() {
        return motorCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_CARDID
     *
     * @param motorCardid the value for TRAFFIC_MOTOR.MOTOR_CARDID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorCardid(String motorCardid) {
        this.motorCardid = motorCardid == null ? null : motorCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_PLATE_NUMBER
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_PLATE_NUMBER
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorPlateNumber() {
        return motorPlateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_PLATE_NUMBER
     *
     * @param motorPlateNumber the value for TRAFFIC_MOTOR.MOTOR_PLATE_NUMBER
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorPlateNumber(String motorPlateNumber) {
        this.motorPlateNumber = motorPlateNumber == null ? null : motorPlateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_ENGINE
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_ENGINE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorEngine() {
        return motorEngine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_ENGINE
     *
     * @param motorEngine the value for TRAFFIC_MOTOR.MOTOR_ENGINE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorEngine(String motorEngine) {
        this.motorEngine = motorEngine == null ? null : motorEngine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_TYPE
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_TYPE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public Integer getMotorType() {
        return motorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_TYPE
     *
     * @param motorType the value for TRAFFIC_MOTOR.MOTOR_TYPE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorType(Integer motorType) {
        this.motorType = motorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_COLOR
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_COLOR
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorColor() {
        return motorColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_COLOR
     *
     * @param motorColor the value for TRAFFIC_MOTOR.MOTOR_COLOR
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorColor(String motorColor) {
        this.motorColor = motorColor == null ? null : motorColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.MOTOR_MODEL
     *
     * @return the value of TRAFFIC_MOTOR.MOTOR_MODEL
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getMotorModel() {
        return motorModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.MOTOR_MODEL
     *
     * @param motorModel the value for TRAFFIC_MOTOR.MOTOR_MODEL
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setMotorModel(String motorModel) {
        this.motorModel = motorModel == null ? null : motorModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.IS_SCRAP
     *
     * @return the value of TRAFFIC_MOTOR.IS_SCRAP
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getIsScrap() {
        return isScrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.IS_SCRAP
     *
     * @param isScrap the value for TRAFFIC_MOTOR.IS_SCRAP
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setIsScrap(String isScrap) {
        this.isScrap = isScrap == null ? null : isScrap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.IS_DELETE
     *
     * @return the value of TRAFFIC_MOTOR.IS_DELETE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.IS_DELETE
     *
     * @param isDelete the value for TRAFFIC_MOTOR.IS_DELETE
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.CREAT_USER_ID
     *
     * @return the value of TRAFFIC_MOTOR.CREAT_USER_ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public Integer getCreatUserId() {
        return creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.CREAT_USER_ID
     *
     * @param creatUserId the value for TRAFFIC_MOTOR.CREAT_USER_ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setCreatUserId(Integer creatUserId) {
        this.creatUserId = creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.CREAT_TIME
     *
     * @return the value of TRAFFIC_MOTOR.CREAT_TIME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.CREAT_TIME
     *
     * @param creatTime the value for TRAFFIC_MOTOR.CREAT_TIME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.EDIT_USER_ID
     *
     * @return the value of TRAFFIC_MOTOR.EDIT_USER_ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public Integer getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.EDIT_USER_ID
     *
     * @param editUserId the value for TRAFFIC_MOTOR.EDIT_USER_ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setEditUserId(Integer editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.EDIT_TIME
     *
     * @return the value of TRAFFIC_MOTOR.EDIT_TIME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public String getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.EDIT_TIME
     *
     * @param editTime the value for TRAFFIC_MOTOR.EDIT_TIME
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setEditTime(String editTime) {
        this.editTime = editTime == null ? null : editTime.trim();
    }


    @Override
    public String toString() {
        return "Motor{" +
                "motorUsername='" + motorUsername + '\'' +
                ", motorMobile='" + motorMobile + '\'' +
                ", motorCardid='" + motorCardid + '\'' +
                ", motorPlateNumber='" + motorPlateNumber + '\'' +
                ", motorEngine='" + motorEngine + '\'' +
                ", motorType=" + motorType +
                ", motorColor='" + motorColor + '\'' +
                ", motorModel='" + motorModel + '\'' +
                ", isScrap='" + isScrap + '\'' +
                ", isDelete='" + isDelete + '\'' +
                ", creatUserId=" + creatUserId +
                ", creatTime='" + creatTime + '\'' +
                ", editUserId=" + editUserId +
                ", editTime='" + editTime + '\'' +
                '}';
    }
}
