package org.family.pojo;

public class MotorKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_MOTOR.ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_MOTOR.ID
     *
     * @return the value of TRAFFIC_MOTOR.ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_MOTOR.ID
     *
     * @param id the value for TRAFFIC_MOTOR.ID
     *
     * @mbggenerated Thu Nov 02 23:00:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}