package org.family.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.USERNAME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.PASSWORD
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.SALT
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.HEAD_PIC
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.MOBILE
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.CARDID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.SEX
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.EMAIL
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.IS_LOCKED
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String isLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.IS_DELETE
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.CREAT_USER_ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private Integer creatUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.CREAT_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.EDIT_USER_ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private Integer editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.EDIT_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_USER.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    private String lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.ID
     *
     * @return the value of TRAFFIC_USER.ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.ID
     *
     * @param id the value for TRAFFIC_USER.ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.USERNAME
     *
     * @return the value of TRAFFIC_USER.USERNAME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.USERNAME
     *
     * @param username the value for TRAFFIC_USER.USERNAME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.PASSWORD
     *
     * @return the value of TRAFFIC_USER.PASSWORD
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.PASSWORD
     *
     * @param password the value for TRAFFIC_USER.PASSWORD
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.SALT
     *
     * @return the value of TRAFFIC_USER.SALT
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.SALT
     *
     * @param salt the value for TRAFFIC_USER.SALT
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.HEAD_PIC
     *
     * @return the value of TRAFFIC_USER.HEAD_PIC
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.HEAD_PIC
     *
     * @param headPic the value for TRAFFIC_USER.HEAD_PIC
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.MOBILE
     *
     * @return the value of TRAFFIC_USER.MOBILE
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.MOBILE
     *
     * @param mobile the value for TRAFFIC_USER.MOBILE
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.CARDID
     *
     * @return the value of TRAFFIC_USER.CARDID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.CARDID
     *
     * @param cardid the value for TRAFFIC_USER.CARDID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.SEX
     *
     * @return the value of TRAFFIC_USER.SEX
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.SEX
     *
     * @param sex the value for TRAFFIC_USER.SEX
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.EMAIL
     *
     * @return the value of TRAFFIC_USER.EMAIL
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.EMAIL
     *
     * @param email the value for TRAFFIC_USER.EMAIL
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.IS_LOCKED
     *
     * @return the value of TRAFFIC_USER.IS_LOCKED
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.IS_LOCKED
     *
     * @param isLocked the value for TRAFFIC_USER.IS_LOCKED
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setIsLocked(String isLocked) {
        this.isLocked = isLocked == null ? null : isLocked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.IS_DELETE
     *
     * @return the value of TRAFFIC_USER.IS_DELETE
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.IS_DELETE
     *
     * @param isDelete the value for TRAFFIC_USER.IS_DELETE
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.CREAT_USER_ID
     *
     * @return the value of TRAFFIC_USER.CREAT_USER_ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public Integer getCreatUserId() {
        return creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.CREAT_USER_ID
     *
     * @param creatUserId the value for TRAFFIC_USER.CREAT_USER_ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setCreatUserId(Integer creatUserId) {
        this.creatUserId = creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.CREAT_TIME
     *
     * @return the value of TRAFFIC_USER.CREAT_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.CREAT_TIME
     *
     * @param creatTime the value for TRAFFIC_USER.CREAT_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.EDIT_USER_ID
     *
     * @return the value of TRAFFIC_USER.EDIT_USER_ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public Integer getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.EDIT_USER_ID
     *
     * @param editUserId the value for TRAFFIC_USER.EDIT_USER_ID
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setEditUserId(Integer editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.EDIT_TIME
     *
     * @return the value of TRAFFIC_USER.EDIT_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.EDIT_TIME
     *
     * @param editTime the value for TRAFFIC_USER.EDIT_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setEditTime(String editTime) {
        this.editTime = editTime == null ? null : editTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_USER.LAST_LOGIN_TIME
     *
     * @return the value of TRAFFIC_USER.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_USER.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for TRAFFIC_USER.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime == null ? null : lastLoginTime.trim();
    }
}