package org.family.mapper;

import org.family.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAFFIC_USER
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAFFIC_USER
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAFFIC_USER
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAFFIC_USER
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAFFIC_USER
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAFFIC_USER
     *
     * @mbggenerated Thu Nov 02 22:40:54 CST 2017
     */
    int updateByPrimaryKey(User record);
}